config/routes.rb
TestApp::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :static_pages
  resources :photos, only: [:index,:new,:create,:show]
  namespace :admin do
    resources :photos
    resources :users
    root to: "photos#index"
  end
  
  get "live", to: "static_pages#index"
  
  root to: "static_pages#index"
  # root to: "static_pages#holding"
  
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base

    # attr_accessible :first_name, :last_name, :city, :country, :website_url, :twitter, :email_address, :published

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController

  before_action :authenticate_user!
  
  respond_to :html, :json
  layout "admin"
  
  def index
    @photos = Photo.paginate(:page => params[:page], :per_page => 6).order("created_at DESC")
  end
  
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else 
      "new"
    end
  end
  
  def show
    @photo = Photo.find(params[:id])
    @photo.update_attributes(published: true) 
  end
  
  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @photo = Photo.find(params[:id])
    @photo.update_attributes(params[:photo])    
  end
  
  def destroy
    @photo = Photo.find(params[:id]).destroy
  end
  
  private

  def photo_params
    params.require(:photo).permit(:first_name, :last_name, :country, :city, :twitter, :website_url, :email_address, :image, :filepicker_url)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  respond_to :html, :json
  layout "admin"
  
  def index
    @users = User.paginate(:page => params[:page], :per_page => 2).order("created_at DESC")
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else 
      "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])    
  end
  
  def destroy
    @user = User.find(params[:id]).destroy
  end
  
  private

  def user_params
    params.require(:user).permit(:full_name, :email_address)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  respond_to :html
  layout "application"
  
  def index
    @photos = Photo.where(published: true).paginate(:page => params[:page], :per_page => 2).order("created_at DESC")
  end
  
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else 
      "new"
    end
  end
  
  def show
    @photo = Photo.find(params[:id])
    @last = Photo.last
    @next = Photo.where("id > ?", @photo.id).where(published: true).pluck(:id).first
    @previous = Photo.where("id < ?", @photo.id).where(published: true).pluck(:id).last
  end
  
  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @photo = Photo.find(params[:id])
    @photo.update_attributes(params[:photo])    
  end
  
  def destroy
    @photo = Photo.find(params[:id]).destroy
  end
  
  private

  def photo_params
    params.require(:photo).permit(:first_name, :last_name, :country, :city, :twitter, :website_url, :email_address, :image, :filepicker_url)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  respond_to :html
  layout "application"

  def index
    @photos = Photo.where(published: true).order("created_at DESC").limit(4)
  end

  def holding
  end

end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/photos/index.html.erb
<section id="container">	
	<div class="panel">	
		<h1>
			ADMIN PANEL
		</h1>
		<table class="nav_bar">
			<td>
			<%= link_to "HOME PAGE", root_url %>
			</td>
			<td>
			<%= link_to "PHOTOS PAGE", photos_path %>
			</td>
			<td> 
			<%=	link_to "LOG OUT", destroy_user_session_path, :method => :delete %> 
			</td>
		</table>
		
		
	</div>

	
		<table id="list">
			<thead>
			<th>IMAGE ID</th>
			<th>PHOTOGRAPH</th>
			<th>NAME</th>
			<th>LOCATION</th>
			<th>CONTACT INFORMATION</th>
			<th>PUBLISHED</th>
			</thead>
	
			<% @photos.each do |img| %>
				
				<tr id="<%= img.id %>">	
							<td>
								<%= img.id %>
							</td>
					
							<td>	
								<%= link_to image_tag("#{img.image}/convert?w=220&h=140&fit=scale"), photo_path(img) %>
							</td>
	
							<td>	
								<%= img.first_name %>
								<%= img.last_name %>
							</td>
							<td>	
								<li><%= img.city %></li>
								<li><%= img.country %></li>
							</td>
							<td>
								<li><%= img.email_address %></li>
								<li><%= img.website_url %></li>
								<li><%= img.twitter %></li>
							</td>
						
							<td class="publish">
								
								<%= link_to img.published? ? "Published" : "Pending", admin_photo_path(img), remote: true, class: "item #{'active' if img.published? }" %>
								
							</td>
						
				
				</tr>
			<% end %>	
		</table>	
		
			<%= will_paginate @photos %>
	
</section>

app/views/admin/photos/show.js.erb
$("#<%= @photo.id %> .publish .item").addClass("active").text("Published");

app/views/admin/photos/update.js.erb
// $("#{@photo.id}").replaceWith("#{ escape_javascript(render :partial => 'controller/item_view', :locals => {:item_view => @item}) }");

$("#container").replaceWith("<%= j ('Hello') %>");

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-10943230-36', 'forestgallery.co');
  ga('send', 'pageview');

</script>

<section id="footer"> 

	<footer>
		
		<nav id="brands"> 
			<a href="http://prote.in" id="cereal" target="_blank">Protein</a>
			<a href="http://readcereal.com/" id="protein" target="_blank">Cereal Mag</a>
			<a href="http://blackcow.co.uk/" id="black-cow" target="_blank">Black Cow Vodka</a>
		</nav>
	
	</footer>

</section>

app/views/layouts/_header.html.erb
<section id="header"> 
	
	<nav id="logo">
		<%= link_to "Home", root_url %>
	</nav>

</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	
<head>
<title>Forest</title>
	<%= stylesheet_link_tag    "admin/application", media: "all" %>
	<%= javascript_include_tag "admin/application" %>
	<%= csrf_meta_tags %>
	<%= filepicker_js_include_tag %>
	<%= favicon_link_tag %>

</head>
<body>
	<div id="main">
		<%= yield %> 
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Forest</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= filepicker_js_include_tag %>
	<%= favicon_link_tag %>
	
	<link rel="stylesheet" href="colorbox.css" />
    <script src="jquery.min.js"></script>
    <script src="jquery.colorbox-min.js"></script>
	<link href='http://fonts.googleapis.com/css?family=Advent+Pro:300,200' rel='stylesheet' type='text/css'>
	
</head>

<body>
	<div id="main">
		<%= render "layouts/header"%>
		
		<% if current_page?(new_user_session_path)%>
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		<% end %>
		<%= yield %> 
		<%= render "layouts/footer"%>

	</div>
	

	
</body>


</html>

app/views/photos/index.html.erb
<section id="seven">
	
	<p>
		A project to collect and curate woodland<br> photography from around the world.
	</p>
	
</section>

<section>	

<div id="list">
	
	<ul> 

	<% @photos.each do |img| %>
		<li>
			<div class="image">	
				<%= link_to image_tag("#{img.image}/convert?&w=680&fit=clip"), photo_path(img) %>
				<div class="image_info">
				<h4>
					<%= img.first_name %>
					<%= img.last_name %>
				<br>			
					<span class="font"><%= img.country %></span>
				</h4>
			</div>	
			</div>
			
			
		</li>
	
	
	<% end %>
	
	</ul>
	
	<%= will_paginate @photos %>
	
</div>	

</section>

app/views/photos/new.html.erb
<section id="form_container">

	<div id="form">
		<h4>
			Upload your forest image here.
		</h4>
	
		<div class="fields">
			<%= simple_form_for @photo do |f| %>
		  	<%= f.input :first_name, placeholder: "First name", label:false, required:true %>
			<%= f.input :last_name, placeholder: "Last name", label:false, required:true%>
			<%= f.input :country, prompt: "Choose your country", label:false %> 
			<%= f.input :city, placeholder: "City", label:false %>	
			<%= f.input :twitter, placeholder: "Twitter handle", label:false %>	
			<%= f.input :website_url, placeholder: "Website url", label:false %>
			<%= f.input :email_address, placeholder: "Email address", label:false %>
			<%= f.input :image, as: :hidden %>
		</div>

	
		<div class="img_upload">
		    <%= f.label :image, "Choose your image:" %>
		<input type="filepicker" data-fp-apikey="AlIx-x_WtQKiw5LrCArBpz" data-fp-mimetypes="image/*" data-fp-container="modal" data-fp-maxsize="2097152" data-fp-services="COMPUTER,FACEBOOK,INSTAGRAM,URL" onchange="$('#photo_image').attr('value', event.fpfile.url);">
		  </div>
	
		<%= f.submit(class: "submit", value:"SUBMIT", onclick: "alert('Thank you for submitting your forest photograph.')") %>
		<% end %>
	
		<a class="terms" href="#window_content"> <strong>Terms & Conditions</strong></a>


	</div>

</section>

app/views/photos/show.html.erb
<div id="image_container">

	<div id="single_img">

		<%= image_tag(@photo.image, alt:@photo.first_name, class:"image_output", width:"100%", height:"auto") %>
	</div>
		
	
	<div id="description">
		<h4>
			<%= @photo.first_name %> <%= @photo.last_name %>
		<br>
		<span class="font"><%=  @photo.country %></span>
		</h4>
	</div>

	
	<div id="navigation">
		<div class="previous">
			<%= link_to "<", photo_path(@previous) unless @previous.blank? %>
		</div>
		<div class="next">
			<%= link_to ">", photo_path(@next) unless @next.blank? %>
		</div>
		
	</div>
	


</div>

app/views/shared/_five.html.erb
<section id="five"> 
	
	<h3>
		THE EVENT
	</h3>
	
	<p>
		<br>The exhibition will take place at the end of September 2013<br> at Protein's London Gallery space, <a href="http://18hewettstreet.co.uk" class="hewett" target="_blank"><strong>18 Hewett Street</strong></a>.
	</p>
	

		<div id="hewett_st_1"></div>
		<div id="hewett_st_2"></div>

</section>

app/views/shared/_four.html.erb
<a id="2"></a>

<section id="four"> 
	
	<h3>
		THE PROJECT
	</h3>
	
	<p>
		<br>The project is a collaboration between <a href="http://prote.in" target="_blank"><strong>Protein</strong></a> and <a href="http://readcereal.com/" target="_blank"><strong>Cereal Magazine</strong></a> to curate a photography<br> exhibition titled, ‘Forest’. Both parties are inviting their readers to submit photos with a forest theme to be<br> considered for inclusion in the exhibition. The chosen images will also be published as a photo essay in <br>Cereal Volume 4. Prints of the final photography will be sold on the night of the event, with all<br> proceeds being donated to the <a href="http://internationaltreefoundation.org/" target="_blank"><strong>International Tree Foundation</strong></a>. 
	</p>

		<div id="protein_logo"></div>
		<div id="x">X</div>
		<div id="cereal_logo"></div>

</section>

app/views/shared/_one.html.erb
<section id="one"> 
	
	<h1 id="logo">
		Forest
	</h1>

</section>

app/views/shared/_six.html.erb
<section id="six"> 
	
	<h3>
		ENTER A PHOTO
	</h3>
	
	<h4>
		Unfortunately, submissions have now closed.

	</h4>

	<p>	
		Thank you to everyone who submitted a forest photograph. We have received an<br> overwhelming number of entries and we will now undertake the almost impossible<br> task of choosing a selection for the exhibition and magazine feature. 
	</p>

	<p> 
		<br>In the meantime, please have a look at the image gallery.



		<!-- To enter your photo, simply use the upload button below.<br> For image guidelines <a class="gallery" href="#window_content"> <strong>click here.</strong></a> -->
	</p>


	<div class="button">
		<%= link_to "SEE MORE", photos_path %>
	</div>

	<div id="window_content">
		<p></p>
	</div>

	<!-- <p> -->
		<!-- <br><small>Submissions open till 5PM GMT 26th August 2013.</small> -->
	<!-- </p> -->

</section>

app/views/shared/_three.html.erb
<section id="three"> 
	
	<h3>
		RECENT SUBMISSIONS
	</h3>

	<div id="recent_photos">

		<% @photos.each do |img| %>
	
			<div class="recent">
				<%= link_to image_tag("#{img.image}/convert?&w=304&h=200&fit=crop"), photo_path(img) %>
			</div>
		
		<% end %>
	
	</div>
	
	<div class="clear_fix"></div>
	
	<div class="button">
		<%= link_to "SEE MORE", photos_path %>
	</div> 
	
	
	
</section>

app/views/shared/_two.html.erb
<section id="two"> 
	
	<div id="box">
		
		<h4>
			A project to collect and curate woodland<br> photography from around the world.
		</h4>
			
		<div class="button">
			<a class="scroll" href="#four">READ MORE</a>
		</div>
		
	</div>
		
</section>

app/views/static_pages/holding.html.erb
<section id="two"> 
	
	<div id="box">
		
		<h4>
			A project to collect and curate woodland<br> photography from around the world.
		</h4>
			
		<div class="button">
			<h8>COMING SOON</h8>
		</div>
		
	</div>
		
</section>

app/views/static_pages/index.html.erb
<%= render "shared/two" %>
<%= render "shared/three" %>
<%= render "shared/four" %>
<%= render "shared/five" %>
<%= render "shared/six" %>